version: "3.5"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

