server:
  port: 6060
  address: 0.0.0.0

registry:
  cache-size: ${CACHE_SIZE:128}
  validity: ${VALIDITY:30}

spring:
  datasource:
    url: jdbc:h2:file:./service-storage/database/db;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS TEST
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    schema: classpath:/schema/schema.sql
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB
