CREATE TABLE namespace
(
    id   INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(127) NOT NULL UNIQUE
);

CREATE TABLE filename
(
    id        INTEGER AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(127) NOT NULL,
    namespace VARCHAR(127) REFERENCES namespace (name) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE registry
(
    id          INTEGER AUTO_INCREMENT PRIMARY KEY,
    registryId  VARCHAR(32)  NOT NULL UNIQUE,
    userDirName VARCHAR(127) NOT NULL
);